backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: assets
collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { name: featured_image, label: Image, widget: image }
      - { name: date, label: Date, widget: datetime, dateFormat: "dddd D MMMM YYYY" }
      - { name: title, label: Title }
      - { name: english_body, label: English, widget: markdown }
      - { name: spanish_body, label: Spanish, widget: markdown }
  # - name: multilang
  #   label: MultiLang
  #   folder: multilang
  #   create: true
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  #   editor:
  #     preview: false
  #   fields:
  #     - { name: featured_image, label: Image, widget: image }
  #     - { name: date, label: Date, widget: datetime, dateFormat: "dddd D MMMM YYYY" }
  #     - { name: title, label: Title }
  #     - { name: english_body, label: English, widget: markdown }
  #     - { name: spanish_body, label: English, widget: markdown }